# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1veua0Y-Q65ToTyp_CRkMXTRY-Usx4inv
"""

listA=["A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","U","V","W","X","Y","Z"]
print(listA)

tupleA=(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26)
print (tupleA)

listB=list(tupleA)
print(listB)

tupleB=tuple(listA)
print(tupleB[20])

alphabet={"A":"1","B":"2","C":"3","D":"4","E":"5","F":"6","G":"7","H":"8","I":"9","J":"10","K":"11","L":"12","M":"13","N":"14","O":"15","P":"16",
            "Q":"17","R":"18","S":"19","T":"20","U":"21","V":"22","W":"23","X":"24","Y":"25","Z":"26"}


def convertHA(alphabet):
  Huruf=input("masukan Huruf =")
  for i in range(len(alphabet)):
    if Huruf in alphabet:
      print(Huruf,":",alphabet[Huruf])
      print("Selesai")
      i = Huruf
      return convertHA(alphabet)
      break
    else :
      print(Huruf, "Tidak di temukan")
      break
convertHA(alphabet)

number={"1":"A","2":"B","3":"C","4":"d","5":"D","6":"F","7":"G","8":"H","9":"I","10":"J","11":"K","12":"L","13":"M","14":"N","15":"O","16":"P",
            "17":"Q","18":"R","19":"S","20":"T","21":"U","22":"V","23":"W","24":"X","25":"Y","26":"Z"}

def convertAH(number):
  angka =input("masukan Angka =")
  for i in range(len(number)):
    if angka in number:
      print(angka,":",number[angka])
      print("Selesai")
      i = angka
      return convertAH(number)
      break
    else :
      print(angka, "Tidak di temukan")
      break
convertAH(number)